In [1]:
import numpy as np
#“axis 0” represents rows and “axis 1” represents columns
#Creating an array
arr=np.array([[2,3,5,1],
             [4,5,3,7],
             [9,5,3,1],
             [4,3,27,7]])
print(arr)

print("arr2")
arr2=np.empty([2,2],dtype=int)
print(arr2)
arr3=np.zeros([3,3],dtype=int)
print(arr3)

print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[[ 2  3  5  1]
 [ 4  5  3  7]
 [ 9  5  3  1]
 [ 4  3 27  7]]
arr2
[[ -210331717   513907688]
 [ -374613766 -2107692804]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32
(4, 4)
2
int32


In [2]:
#First two row with alternate columns
sliced_arr=arr[:2,::2]
sliced_arr

array([[2, 5],
       [4, 3]])

In [3]:
#Indexing an array
index_arr=arr[1,2]
index_arr


3

In [4]:
# Basic Operation
arr1=np.array([[1,2,3],
               [5,67,7],
              [2,78,8]])
print("The array after opearion is \n",arr+1)
print("The sum of array after opearion is \n",arr.sum())
print("Rowwise min value",arr1.min(axis =1))
print("columnwise max value",arr1.max(axis =0))#column



The array after opearion is 
 [[ 3  4  6  2]
 [ 5  6  4  8]
 [10  6  4  2]
 [ 5  4 28  8]]
The sum of array after opearion is 
 89
Rowwise min value [1 5 2]
columnwise max value [ 5 78  8]


In [5]:
#Methods
from numpy import transpose
sqr=np.sqrt(arr)
sqr
transpose=arr.T
transpose

array([[ 2,  4,  9,  4],
       [ 3,  5,  5,  3],
       [ 5,  3,  3, 27],
       [ 1,  7,  1,  7]])

In [6]:
#Flatten ,reshape and arrange Method
arr4=np.arange(4,12)
print(arr4)
print("Array having 2 rows and 4 columns\n",arr4.reshape(2,4))
print("Flatten",arr1.flatten())
arr5=np.arange(10,2,-2)
arr5

[ 4  5  6  7  8  9 10 11]
Array having 2 rows and 4 columns
 [[ 4  5  6  7]
 [ 8  9 10 11]]
Flatten [ 1  2  3  5 67  7  2 78  8]


array([10,  8,  6,  4])

In [7]:
#indexing multiple
print(arr5[np.array([2,1,-3])])
print(arr[...,1])
print(arr5[arr5>6])

[6 8 8]
[3 5 5 3]
[10  8]


In [8]:
arr6=np.array([[5,5],[4,3],[10,10]])
b=arr6.sum(-1)
print(arr6[b%10==0])

[[ 5  5]
 [10 10]]


In [9]:
#iterting array C and F class 
for i in np.nditer(arr6,order="F"):
    print(i)

5
4
10
5
3
10


In [10]:
for i in np.nditer(arr6,op_flags=['readwrite']):
    i[...]=i**2
print(arr6)

[[ 25  25]
 [ 16   9]
 [100 100]]


In [11]:
#string Operation
print(np.char.lower(["INDIA","COUNTRY"]))
print(np.char.split('India is my country'))
print(np.char.join([',',':'],['india','Country']))

#counting a substring 
arr7=np.array(['kp','SP','PP'])
print(np.char.count(arr7,'kp'))
print(np.char.rfind(arr7,'SP'))

['india' 'country']
['India', 'is', 'my', 'country']
['i,n,d,i,a' 'C:o:u:n:t:r:y']
[1 0 0]
[-1  0 -1]


In [14]:
#Searching ,sorting ,counting
print("Sort by column")
print(np.sort(arr,axis=0))
print("Sort by rows")
print(np.sort(arr,axis=1))
print(np.sort(arr,axis=-1))
print(np.sort(arr,axis=None))
print(np.argsort(arr6,axis =0)) #Sort by index

Sort by column
[[ 2  3  3  1]
 [ 4  3  3  1]
 [ 4  5  5  7]
 [ 9  5 27  7]]
Sort by rows
[[ 1  2  3  5]
 [ 3  4  5  7]
 [ 1  3  5  9]
 [ 3  4  7 27]]
[[ 1  2  3  5]
 [ 3  4  5  7]
 [ 1  3  5  9]
 [ 3  4  7 27]]
[ 1  1  2  3  3  3  3  4  4  5  5  5  7  7  9 27]
[[1 1]
 [0 0]
 [2 2]]


In [15]:
a = np.array([9, 3, 1, 3, 4, 3, 6])
b = np.array([4, 6, 9, 2, 1, 8, 7]) 
print('column a, column b')
for (i, j) in zip(a, b):
    print(i, ' ', j)

column a, column b
9   4
3   6
1   9
3   2
4   1
3   8
6   7


In [21]:
print(arr4.reshape(2,4))
print(np.argmax(arr4))
print(np.argmax(arr4,axis=0))
#print(np.argmax(arr4,axis=1))


[[ 4  5  6  7]
 [ 8  9 10 11]]
7
7


In [26]:
arr8=np.arange(10)
arr8
ab = arr8[arr8%2==1]  #return odd numbers 
print(ab)
arr8[arr8%2==1]=-1  #Replace odd numbers with -1
arr8

[1 3 5 7 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])