In [39]:
import numpy as np
#Creating an array
arr=np.array([[2,3,5,1],
             [4,5,3,7],
             [9,5,3,1],
             [4,3,27,7]])
print(arr)

print("arr2")
arr2=np.empty([2,2],dtype=int)
print(arr2)
arr3=np.zeros([3,3],dtype=int)
print(arr3)

print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[[ 2  3  5  1]
 [ 4  5  3  7]
 [ 9  5  3  1]
 [ 4  3 27  7]]
arr2
[[   48314353   500067001]
 [ 1338957540 -1163084920]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32
(4, 4)
2
int32


In [40]:
#First two row with alternate columns
sliced_arr=arr[:2,::2]
sliced_arr

array([[2, 5],
       [4, 3]])

In [41]:
#Indexing an array
index_arr=arr[1,2]
index_arr


3

In [42]:
# Basic Operation
arr1=np.array([[1,2,3],
               [5,67,7],
              [2,78,8]])
print("The array after opearion is \n",arr+1)
print("The sum of array after opearion is \n",arr.sum())
print("Rowwise min value",arr1.min(axis =1))
print("columnwise max value",arr1.max(axis =0))#column



The array after opearion is 
 [[ 3  4  6  2]
 [ 5  6  4  8]
 [10  6  4  2]
 [ 5  4 28  8]]
The sum of array after opearion is 
 89
Rowwise min value [1 5 2]
columnwise max value [ 5 78  8]


In [43]:
#Methods
from numpy import transpose
sqr=np.sqrt(arr)
sqr
transpose=arr.T
transpose

array([[ 2,  4,  9,  4],
       [ 3,  5,  5,  3],
       [ 5,  3,  3, 27],
       [ 1,  7,  1,  7]])

In [51]:
#Flatten ,reshape and arrange Method
arr4=np.arange(4,12)
print(arr4)
print("Array having 2 rows and 4 columns\n",arr4.reshape(2,4))
print("Flatten",arr1.flatten())

[ 4  5  6  7  8  9 10 11]
Array having 2 rows and 4 columns
 [[ 4  5  6  7]
 [ 8  9 10 11]]
Flatten [ 1  2  3  5 67  7  2 78  8]
